[tools]
"aqua:atuinsh/atuin"    = "latest"
"aqua:getsops/sops"     = "latest"
"cargo:atac"            = "latest"
"cargo:twm"             = "latest"
"cargo:tlrc"            = "latest"
duf                     = "latest"
stern                   = "latest"
usage                   = "latest"
"ubi:bootandy/dust"     = "latest"
"ubi:dandavison/delta"  = "latest"
"ubi:SuperCuber/dotter" = "latest"
"ubi:tamasfe/taplo"     = "latest"
zoxide                  = "latest"

[plugins]
